blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogView, BlogDetailView

app_name = BlogConfig.name
urlpatterns = [
    path('', cache_page(60)(BlogView.as_view()), name='list_blog'),
    path('detail/<int:pk>', BlogDetailView.as_view(), name='detail_blog')
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
      path('admin/', admin.site.urls),
      path('', include('mailing.urls', namespace='mailing')),
      path('', include('core.urls', namespace='core')),
      path('blog/', include('blog.urls', namespace='blog')),
      path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from core.apps import CoreConfig
from core.views import contacts, home

app_name = CoreConfig.name

urlpatterns = [
    path('contacts/', cache_page(60)(contacts), name='contacts'),
    path('', home, name='home'),
]

mailing/urls.py
from django.urls import path

from mailing.apps import MailingConfig
from mailing.views import (MailingListView, MailingCreateView, MailingUpdateView, MailingDeleteView,
                           CustomerListView, CustomerCreateView, CustomerUpdateView, CustomerDetailView,
                           CustomerDeleteView, hide_mailing, MailingDetail, LogView)

app_name = MailingConfig.name

urlpatterns = [
    path('mailing/', MailingListView.as_view(), name='list_mailing'),
    path('hide_mailing/', hide_mailing, name='hide_mailing'),
    path('mailing/create/', MailingCreateView.as_view(), name='create_mailing'),
    path('mailing/detail/<int:pk>', MailingDetail.as_view(), name='detail_message'),
    path('mailing/update/<int:pk>', MailingUpdateView.as_view(), name='update_mailing'),
    path('mailing/delete/<int:pk>', MailingDeleteView.as_view(), name='delete_mailing'),
    path('mailing/log', LogView.as_view(), name='list_log'),

    path('customer/', CustomerListView.as_view(), name='list_customer'),
    path('customer/detail/<int:pk>', CustomerDetailView.as_view(), name='detail_customer'),
    path('customer/create/', CustomerCreateView.as_view(), name='create_customer'),
    path('customer/update/<int:pk>', CustomerUpdateView.as_view(), name='update_customer'),
    path('customer/delete/<int:pk>', CustomerDeleteView.as_view(), name='delete_customer'),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView

app_name = UsersConfig.name
urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
]

mailing/models.py
from django.db import models

from users.models import User

NULLABLE = {'blank': True, 'null': True}


class Customer(models.Model):
    email = models.EmailField(max_length=150, verbose_name='почта', unique=True)
    first_name = models.CharField(max_length=150, verbose_name='имя', **NULLABLE)
    last_name = models.CharField(max_length=150, verbose_name='фамилия', **NULLABLE)
    comment = models.TextField(verbose_name='комментарий', **NULLABLE)

    def __str__(self):
        return f'{self.last_name} ({self.email})'

    class Meta:
        verbose_name = 'клиент'
        verbose_name_plural = 'клиенты'


class Mailing(models.Model):
    FREQUENCY_CHOICES = [
        ('O', 'ONCE'),
        ('D', 'DAY'),
        ('W', 'WEEK'),
        ('M', 'MONTH'),
    ]

    STATUS_CHOICES = [
        ('CR', 'CREATED'),
        ('LA', 'LAUNCHED'),
        ('CO', 'COMPLETED'),
    ]
    distribution_settings = models.TimeField(verbose_name='время рассылки', default='10:00')
    frequency = models.CharField(max_length=10, verbose_name='периодичность', choices=FREQUENCY_CHOICES, default='O')
    status = models.CharField(max_length=15, verbose_name='статус рассылки', choices=STATUS_CHOICES,
                              default=STATUS_CHOICES[0][0])
    is_block = models.BooleanField(verbose_name='заблокирована', default=False)
    last_mailing_time = models.DateTimeField(verbose_name='последняя рассылка', **NULLABLE)

    customer = models.ManyToManyField(Customer, verbose_name='клиент')
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='владелец рассылки', default=1)

    def __str__(self):
        return self.status

    class Meta:
        verbose_name = 'рассылка'
        verbose_name_plural = 'рассылки'
        ordering = ['distribution_settings']

        permissions = [
            (
                'set_block',
                'Can block mailing'
            )
        ]


class Message(models.Model):
    title = models.CharField(max_length=100, verbose_name='тема')
    body = models.TextField(verbose_name='содержание', **NULLABLE)

    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE, verbose_name='рассылка', **NULLABLE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'сообщение'
        verbose_name_plural = 'сообщения'


class Log(models.Model):
    STATUS_CHOICES = [
        ('S', 'SUCCESSFUL'),
        ('UNS', 'UNSUCCESSFUL'),
    ]
    last_try = models.DateTimeField(verbose_name='время попытки', auto_now_add=True)
    status = models.CharField(verbose_name='статус попытки', choices=STATUS_CHOICES, max_length=20)
    response = models.TextField(verbose_name='ответ сервера')

    mailing_settings = models.ForeignKey(Mailing, on_delete=models.CASCADE, **NULLABLE)

    def __str__(self):
        return self.status

    class Meta:
        verbose_name = 'лог'
        verbose_name_plural = 'логи'

mailing/forms.py
import datetime
import time

from django import forms
from django.core.exceptions import ValidationError

from mailing.models import Message, Mailing, Customer


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class MessageForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Message
        fields = ('title', 'body',)


class MailingForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Mailing
        fields = ('distribution_settings', 'frequency',)

    # def clean_distribution_settings(self):
    #     cleaned_data = self.cleaned_data.get('distribution_settings')
    #
    #     # if cleaned_data.strftime() not in ('%H:%M:%S', '%H:%M'):
    #     if datetime.datetime.strptime(str(cleaned_data), '%H:%M'):
    #         raise forms.ValidationError('Ошибка формата времени.')
    #
    #     return cleaned_data


class CustomerForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Customer
        fields = '__all__'

mailing/views.py
import datetime

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.forms import inlineformset_factory
from django.http import Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DeleteView, UpdateView, DetailView

from mailing.forms import MessageForm, MailingForm, CustomerForm
from mailing.models import Message, Mailing, Customer, Log
from mailing.services import send_mailing


class MailingListView(LoginRequiredMixin, ListView):
    model = Mailing

    def get_queryset(self):
        queryset = super().get_queryset()
        if not self.request.user.is_staff:
            queryset = queryset.filter(owner=self.request.user.pk)
        return queryset

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        context_data['message'] = Message.objects.all()
        return context_data


class MailingCreateView(LoginRequiredMixin, CreateView):
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('mailing:list_mailing')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)

        MessageFormset = inlineformset_factory(Mailing, Message, form=MessageForm)
        if self.request.method == 'POST':
            context_data['formset'] = MessageFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = MessageFormset(instance=self.object)

        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']

        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()

        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        send_mailing(message=Message.objects.get(mailing_id=self.object.id))
        return super().form_valid(form)


class MailingUpdateView(LoginRequiredMixin, UpdateView):
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('mailing:list_mailing')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.owner != self.request.user and not self.request.user.is_staff:
            raise Http404
        return self.object

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        MessageFormset = inlineformset_factory(Mailing, Message, form=MessageForm)
        if self.request.method == 'POST':
            context_data['formset'] = MessageFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = MessageFormset(instance=self.object)

        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()

        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)


class MailingDeleteView(LoginRequiredMixin, DeleteView):
    model = Mailing
    success_url = reverse_lazy('mailing:list_mailing')


class MailingDetail(LoginRequiredMixin, DetailView):
    model = Mailing

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['message'] = Message.objects.get(mailing=self.object)
        return context_data


class CustomerListView(LoginRequiredMixin, ListView):
    model = Customer


class CustomerDetailView(LoginRequiredMixin, DetailView):
    model = Customer
    form_class = CustomerForm
    permission_required = ''


class CustomerCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Customer
    fields = ('email', 'last_name', 'first_name')
    success_url = reverse_lazy('mailing:list_customer')
    permission_required = 'mailing.add_customer'


class CustomerUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Customer
    fields = ('email', 'last_name', 'first_name')
    success_url = reverse_lazy('mailing:list_customer')
    permission_required = 'mailing.change_customer'


class CustomerDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Customer
    success_url = reverse_lazy('mailing:list_customer')
    permission_required = 'mailing.delete_customer'


def hide_mailing(request):
    if 'mailing_id' in request.GET:
        mailing_id = request.GET.get('mailing_id')
        mailing = Mailing.objects.get(id=mailing_id)
        mailing.save()
        mailing.is_block = True
        mailing.save()
        return redirect('mailing:list_mailing')

    mailings = Mailing.objects.all()
    context = {'mailing': mailings}
    return render(request, 'mailing:mailing_list.html', context)


class LogView(LoginRequiredMixin, ListView):
    model = Log

mailing/templates/mailing/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>{% if title %}{{ title }} - {% endif %}Сервис рассылок</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/jumbotron.css' %}" rel="stylesheet">
    <link href="{% static 'css/sticky-footer.css' %}" rel="stylesheet">
</head>

<body>

<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="{% url 'core:home' %}">Skychimp</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
            aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'mailing:list_mailing' %}">Рассылки<span
                        class="sr-only"></span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'mailing:list_customer' %}">Клиенты</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'core:contacts' %}">Контакты</a>
            </li>
            <li class="nav-item">
                {% if user.is_authenticated %}
                <div class="btn-group" role="group">
                    <a class="nav-link" href="{% url 'users:profile' %}">Профиль</a>
                    <a class="nav-link" href="{% url 'users:logout' %}">Выйти ({{ user.email }})</a>
                </div>
                {% else %}
                <div class="btn-group" role="group">
                    <a class="nav-link" href="{% url 'users:login' %}">Войти</a>
                    <a class="nav-link" href="{% url 'users:register' %}">Зарегистрироваться</a>
                </div>
                {% endif %}
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'blog:list_blog' %}">Блог</a>
            </li>
    </div>
    </li>
    </ul>
    </div>
</nav>

<main role="main">

    {% block content%}
    {% endblock %}

</main>

<footer class="footer">
    <div class="container">
        <span>&copy; Skychimp 2023</span>
    </div>
</footer>


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/holder.min.js' %}"></script>
</body>
</html>

mailing/templates/mailing/customer_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
<form method="post">
    <div class="modal modal-sheet position-static d-block bg-body-secondary p-4 py-md-5" tabindex="-1" role="dialog"
         id="modalChoice">
        <div class="modal-dialog" role="document">
            <div class="modal-content rounded-3 shadow">
                <div class="modal-body p-4 text-center">
                    <h5 class="mb-0">Вы действительно хотите удалить клиента?</h5>
                    <p class="mb-0">Понимаем.</p>
                </div>
                <div class="modal-footer flex-nowrap p-0">
                    {% csrf_token %}
                    <button type="submit"
                            class="btn btn-lg btn-link fs-6 text-decoration-none col-6 py-3 m-0 rounded-0 border-end">
                        <strong>Удалить</strong></button>
                    <a href="{% url 'mailing:list_customer' %}" type="button" class="btn btn-lg btn-link fs-6 text-decoration-none col-6 py-3 m-0 rounded-0"
                            data-bs-dismiss="modal">Галя, отмена
                    </a>
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}

mailing/templates/mailing/customer_detail.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-8 mt-5">
            <div class="card mb-3" style="width 18rem;">
                <div class="card-body">
                    <h5 class="card-title text-center">
                        {{ object.last_name }} {{ object.first_name }}
                    </h5>
                    <p class="card-text text-start">
                        <u>Почта:</u> {{ object.email }}
                        <br>
                        {% if object.comment is None %}
                            <u>Комментарий:</u> &mdash;
                        {% else %}
                            <u>Комментарий:</u> {{ object.comment }}

                        {% endif %}
                    </p>
                </div>
                <div class="card-footer text-center">
                    <a class="btn btn-outline-primary" href="{% url 'mailing:update_customer' object.pk %}">Изменить</a>
                    <a class="btn btn-outline-danger" href="{% url 'mailing:delete_customer' object.pk %}">Удалить</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/customer_form.html
{% extends 'mailing/base.html' %}

{% block content %}
<form method="post" class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                {% if object %}
                    Редактировать
                {% else %}
                    Добавить
                {% endif %}
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">
                    {% if object %}
                        Сохранить
                    {% else %}
                        Добавить
                    {% endif %}
                </button>
            </div>
        </div>
    </div>
</form>
{% endblock %}

mailing/templates/mailing/customer_list.html
{% extends 'mailing/base.html' %}

{% block content %}

<div class="col-lg-6 col-xxl-4 my-5 mx-auto">
    <div class="d-grid gap-2">
        <button class="btn btn-outline-secondary" type="button">Не добавлять...</button>
        <a href="{% url 'mailing:create_customer' %}" class="btn btn-primary">Добавить нового клиента</a>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    Клиенты
                </div>
                <div class="card-body">
                    <table class="table">
                        <tr>
                            <th>Фамилия</th>
                            <th>Имя</th>
                            <th>Почта</th>
                            <th></th>
                        </tr>
                        {% for object in object_list %}
                        <tr>
                            <td>{{ object.last_name }}</td>
                            <td>{{ object.first_name }}</td>
                            <td>{{ object.email }}</td>
                            <td>
                                <a href="{% url 'mailing:detail_customer' object.pk %}" class="btn btn-dark">
                                    Перейти &#127793;
                                </a></td>
                        </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/log_list.html
{% extends 'mailing/base.html' %}

{% block content %}

<div class="container">
    <div class="row">
            <div class="col-12 mt-5">
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">
                            Логи рассылок
                        </div>
                    </div>
                    <div class="card-body">
                        <table class="table">
                            <tr>
                                <th>Последняя попытка</th>
                                <th>Статус</th>
                                <th>Ответ</th>
                                <th></th>
                            </tr>
                            {% for object in object_list %}
                                <tr>
                                    <td>{{ object.last_try }}</td>
                                    <td>{{ object.status }}</td>
                                    <td>{{ object.response }}</td>
                                </tr>
                            {% endfor %}
                        </table>
                    </div>
                </div>
            </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/mailing_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
<form method="post">
    <div class="modal modal-sheet position-static d-block bg-body-secondary p-4 py-md-5" tabindex="-1" role="dialog"
         id="modalChoice">
        <div class="modal-dialog" role="document">
            <div class="modal-content rounded-3 shadow">
                <div class="modal-body p-4 text-center">
                    <h5 class="mb-0">Вы действительно хотите удалить рассылку?</h5>
                    <p class="mb-0">Напишите нам, если вам угрожали.</p>
                </div>
                <div class="modal-footer flex-nowrap p-0">
                    {% csrf_token %}
                    <button type="submit"
                            class="btn btn-lg btn-link fs-6 text-decoration-none col-6 py-3 m-0 rounded-0 border-end">
                        <strong>Удалить</strong></button>
                    <a href="{% url 'mailing:list_mailing' %}" type="button"
                       class="btn btn-lg btn-link fs-6 text-decoration-none col-6 py-3 m-0 rounded-0">Галя, отмена
                    </a>
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}

mailing/templates/mailing/mailing_detail.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-2"></div>
        <div class="col-8 mt-5">
            <div class="card mb-3" style="width 18rem;">
                <div class="card-header text-center">
                    <div class="card-title">
                        {{ message.title }}
                    </div>
                </div>
                <div class="card-body">
                    <p class="card-text text-start">
                        {{ message.body }}
                </div>
                <div class="card-footer text-center">
                    Время рассылки {{ object.distribution_settings }}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/mailing_form.html
{% extends 'mailing/base.html' %}

{% block content %}
<form method="post" class="row" enctype="multipart/form-data">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                {% if object %}
                Редактировать
                {% else %}
                Добавить
                {% endif %}
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">
                    {% if object %}
                    Сохранить
                    {% else %}
                    Добавить
                    {% endif %}
                </button>
            </div>
        </div>
    </div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                Сообщение
            </div>
            <div class="card-body">
                {{ formset.management_form }}
                {% for form in formset.forms %}
                    {{ form.as_p }}
                {% endfor %}
            </div>
        </div>
    </div>
</form>
{% endblock %}

mailing/templates/mailing/mailing_list.html
{% extends 'mailing/base.html' %}

{% block content %}

<div class="col-lg-6 col-xxl-4 my-5 mx-auto">
    <div class="d-grid gap-2">
        <a href="{% url 'mailing:list_log' %}" class="btn btn-outline-secondary" type="button">Просмотр логов по рассылкам</a>
        <a href="{% url 'mailing:create_mailing' %}" class="btn btn-primary">Добавить сообщение для рассылки</a>
    </div>
</div>

<div class="container">
    <div class="row">

        {% for object in object_list %}
            {% if not object.mailing.is_block %}
                <div class="col-12 mt-5">
                    <div class="card">
                        <div class="card-header text-center">
                            Рассылка на {{ object.distribution_settings }}
                        </div>
                        <div class="card-body text-center">
                            <div class="text">Статус рассылки: {{ object.status }}</div>
                            <div class="text-muted">{{ object.owner.email }}</div>
                        </div>
                        <div class="card-footer">
                            <a class="btn btn-outline-primary"
                               href="{% url 'mailing:detail_message' object.pk %}">Посмотреть</a>

                            <a class="btn btn-outline-primary" href="{% url 'mailing:update_mailing' object.pk %}">Изменить</a>
                            <a class="btn btn-outline-danger" href="{% url 'mailing:delete_mailing' object.pk %}">Удалить</a>
                            {% if perms.mailing.set_block_mailingsettings %}
                                {% csrf_token %}
                                <div class="post">
                                    <a href="{% url 'mailing:hide_mailing' %}?mailing_id={{ object.pk }}">Отключить</a>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endif %}
        {% endfor %}

    </div>
</div>
{% endblock %}

mailing/templates/mailing/message_detail.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-8 mt-5">
            <div class="card mb-3" style="width 18rem;">
                <div class="card-body">
                    <h5 class="card-title text-center">
                        {{ object.title }}
                    </h5>
                    <p class="card-text text-start">
                        {{ object.body }}
                </div>
                <div class="card-footer text-center">
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}