blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogView, BlogDetailView

app_name = BlogConfig.name
urlpatterns = [
    path('', cache_page(60)(BlogView.as_view()), name='list_blog'),
    path('detail/<int:pk>', BlogDetailView.as_view(), name='detail_blog')
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
      path('admin/', admin.site.urls),
      path('', include('mailing.urls', namespace='mailing')),
      path('', include('core.urls', namespace='core')),
      path('blog/', include('blog.urls', namespace='blog')),
      path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from core.apps import CoreConfig
from core.views import contacts, home

app_name = CoreConfig.name

urlpatterns = [
    path('contacts/', cache_page(60)(contacts), name='contacts'),
    path('', home, name='home'),
]

mailing/urls.py
from django.urls import path

from mailing.apps import MailingConfig
from mailing.views import (MailingListView, MailingCreateView, MailingUpdateView, MailingDeleteView,
                           CustomerListView, CustomerCreateView, CustomerUpdateView, CustomerDetailView,
                           CustomerDeleteView, hide_mailing, MailingDetail, LogView)

app_name = MailingConfig.name

urlpatterns = [
    path('mailing/', MailingListView.as_view(), name='list_mailing'),
    path('hide_mailing/', hide_mailing, name='hide_mailing'),
    path('mailing/create/', MailingCreateView.as_view(), name='create_mailing'),
    path('mailing/detail/<int:pk>', MailingDetail.as_view(), name='detail_message'),
    path('mailing/update/<int:pk>', MailingUpdateView.as_view(), name='update_mailing'),
    path('mailing/delete/<int:pk>', MailingDeleteView.as_view(), name='delete_mailing'),
    path('mailing/log', LogView.as_view(), name='list_log'),

    path('customer/', CustomerListView.as_view(), name='list_customer'),
    path('customer/detail/<int:pk>', CustomerDetailView.as_view(), name='detail_customer'),
    path('customer/create/', CustomerCreateView.as_view(), name='create_customer'),
    path('customer/update/<int:pk>', CustomerUpdateView.as_view(), name='update_customer'),
    path('customer/delete/<int:pk>', CustomerDeleteView.as_view(), name='delete_customer'),
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

from blog.models import Blog
from mailing.models import Message, Mailing, Customer


# Create your views here.
def contacts(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        message = request.POST.get('message')
        print(f'Новый контакт!\n{name} ({email}) написал: {message}\n')
    return render(request, 'core/contacts.html')


def home(request):
    mailing_count = Mailing.objects.all()
    active_mailing_count = Mailing.objects.filter(status='CR')
    unique_clients = Customer.objects.all()
    blog = Blog.objects.all()[:3]

    context = {
        'mailing_count': mailing_count,
        'active_mailing_count': active_mailing_count,
        'unique_clients': unique_clients,
        'blog': blog
    }
    return render(request, 'core/home.html', context)

core/templates/core/contacts.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class="container">
        <div class="row gx-5 justify-content-center">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <table class="table table-light">
                            <tr>
                                <td class="w-25">Почта</td>
                                <td>wow@sky.pro</td>
                            </tr>
                            <tr>
                                <td class="w-25">Телефон</td>
                                <td>8-800-555-35-35</td>
                            </tr>
                            <tr>
                                <td class="w-25">ИП</td>
                                <td>Есть</td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col-6">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                    </div>
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="name">Имя</label>
                                <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"/>
                            </div>
                            <div class="mb-3">
                                <label for="email">Почта</label>
                                <input type="text" name="email" class="form-control" id="email"
                                       placeholder="Почта"/>
                            </div>
                            <div class="mb-3">
                                <label for="message">Сообщение</label>
                                <textarea type="text" name="message" class="form-control" id="message"
                                          placeholder="Сообщение"></textarea>
                            </div>
                            <input type="submit" value="Отправить" class="btn btn-lg btn-block btn-outline-primary"/>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

core/templates/core/home.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="jumbotron">
    <div class="container">
        <h6 class="display-4">Удобный сервис рассылок</h6>
        <h4 class="text-muted">- количество рассылок всего: {{ mailing_count|length }}</h4>
        <h4 class="text-muted">- количество активных рассылок: {{ active_mailing_count|length}}</h4>
        <h4 class="text-muted">- количество уникальных клиентов для рассылок: {{ unique_clients|length }}</h4>
        <a class="btn btn-lg btn-primary" href="{% url 'mailing:list_mailing' %}" role="button">К рассылкам &raquo;</a>
    </div>
</div>

<div class="container">
    <div class="row mt-5    ">
        {% for object in blog %}
        <div class="col-md-4">
                <img src="/media/{{ object.preview }}" height="250" width="250"
                     alt="Все будет, но не сразу">
            <h2>{{ object.title }}</h2>
            <p>{{ object.body|slice:100}}</p>
            <p><a class="btn btn-secondary" href="{% url 'blog:detail_blog' object.pk %}" role="button">Читать далее
                &raquo;</a></p>
        </div>
        {% endfor %}
    </div>
    <hr>
</div>
{% endblock%}